{% set name = "napari-bil-data-viewer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-bil-data-viewer-{{ version }}.tar.gz
  sha256: 193eaa5a74c5548022131553506163a897caef87901df3f39dcbf6069fcac782

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aiohttp
    - beautifulsoup4
    - dask-core
    - fsspec
    - imagecodecs
    - napari
    - napari-plugin-engine >=0.1.4
    - python >=3.8
    - requests
    - scikit-image

test:
  imports:
    - napari_bil_data_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brain-image-library/napari-bil-data-viewer
  summary: Napari plugin for viewing Brain Image Library datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
